import { VerticalFeatureRow } from '../feature/VerticalFeatureRow';
import { Section } from '../layout/Section';
import Feature2SVG from '../svgs/Feature2SVG';
import Feature3SVG from '../svgs/Feature3SVG';
import FeatureSVG from '../svgs/FeatureSVG';

const VerticalFeatures = () => (
  <Section
    title="Project Astra"
    description="Astra demonstrates an end-to-end working prototype of using DNS data primarily domain names to detect potential suspicious domains names generated by DGAs embedded in the malicious code running in the compromised systems. "
  >
    <VerticalFeatureRow
      title="Threats"
      description="Threat actors use different techniques, specifically algorithmically generated domains (AGDs), to bypass traditional security devices; and (2) about methods of detecting DGAs (domain generation algorithms) using NVIDIA Morpheus-based machine learning model to mitigate threats. Working knowledge of DNS, network security, and basic concepts of data analysis using ML will be helpful."
      imageComponent={<FeatureSVG />}
      imageAlt="First feature alt text"
    />
    <VerticalFeatureRow
      title="Machine Learning"
      description="An ensemble of deep learning and traditional ML methods can better detect AGDs in real time and subvert malware attacks that use DGAs. We'll demonstrate end-to-end working prototype of using DNS data, primarily domain names, to detect suspicious domains names potentially generated by DGAs embedded in malicious code running on the compromised systems."
      imageComponent={<Feature2SVG />}
      imageAlt="Second feature alt text"
      reverse
    />
    <VerticalFeatureRow
      title="Team"
      customDescription={
        <section>
          <section className="pb-4">
            <div className="text-lg font-medium">Principal Researcher</div>
            <div className="text-base font-light">Aditya K Sood</div>
          </section>
          <section className="pb-4">
            <div className="text-lg font-medium">Sponser</div>
            <div className="text-base font-light">Renuka Nadkarni</div>
          </section>
          <section className="pb-4">
            <div className="text-lg font-medium">Project Team</div>
            <ul>
              <li className="text-base font-light">
                Bharathasimha Reddy Devarapally
              </li>
              <li className="text-base font-light">Srilekha Talluri</li>
              <li className="text-base font-light">Amit Nagal</li>
              <li className="text-base font-light">Ruthvik Reddy SL </li>
              <li className="text-base font-light">Rohit Chaturvedi</li>
            </ul>
          </section>
        </section>
      }
      imageComponent={<Feature3SVG />}
      imageAlt="Third feature alt text"
    />
  </Section>
);

export { VerticalFeatures };
